// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyipoogjzfxmzyjsgilf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95aXBvb2dqemZ4bXp5anNnaWxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMDgzMDEsImV4cCI6MjA2OTU4NDMwMX0.osqxq4wdG49wAJoFwtdACQ79sMEGyjIaHw9g7HOQpWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});